### ISSUE TITLE
[NumberGuesser] Stopwatch

### ISSUE THREAD

**Issue by pavel-b-novikov** [gipertech/nsudotnet#1]
Похвально что вы знаете об этом классе. Однако в данной задаче он выглядит "вырванным из контекста". 

Для чего он все-таки используется "в дикой природе"?

**Comment by gipertech** [comment]
Прошу прощения за задержку. Только приехали с конференции в Томске, откуда даже привезли диплом)
Класс Stopwatch измеряет на самом нижнем, из возможных уровней временного механизма. То есть его целесообразно использовать там, где требуется достаточно высокая точность измерений, при условии наличия HPET. Например при отладке, тестированию производительности кода, сбору точной статистики. Так как в данной программе точность вообще несущественна, то, вероятно, более оптимальны менее хардкорные, но более быстрые средства.

**Comment by pavel-b-novikov** [comment]
Верно. Шарите.
