### ISSUE TITLE
[PerlinNoise] Именование!

### ISSUE THREAD

**Issue by pavel-b-novikov** [gipertech/nsudotnet#2]
Прочитайте пожалуйста лекцию, в которой говорилось про правила именования. И поправьте задачу соответствующим образом.

**Comment by gipertech** [comment]
Ага, исправил приватные поля. Про приватным константам я толком примеров не нашел, но решарпер только на такое наименование не ругается

**Comment by pavel-b-novikov** [comment]
и_так_сойдет.jpg
