### ISSUE TITLE
[LinesCounter] Неправильно работает

### ISSUE THREAD

**Issue by pavel-b-novikov** [gipertech/nsudotnet#4]
Алгоритм подсчета строк неверный. Многострочные комментарии не поддерживаются

**Comment by gipertech** [comment]
Алгоритм переделан

**Comment by pavel-b-novikov** [comment]
Вы на ФИТ учитесь?

**Comment by gipertech** [comment]
Да. Так плохо? Изначально неправильный алгоритм выбрал, но оттестировал и добил. Где-то на середине понял правильную реализацию. Предоставить ее?

**Comment by pavel-b-novikov** [comment]
предоставьте, чо уж
Просто ну.. тримить строки-то зачем? вырезать из них табуляции, пробелы... InfexOf, удалять что-то... похоже на МехМатовский подход.

**Comment by gipertech** [comment]
Более красивый код. Но и алгоритм менее пафосен)
