### ISSUE TITLE
[Perlin] Алгоритм

### ISSUE THREAD

**Issue by pavel-b-novikov** [gipertech/nsudotnet#5]
Ваш алгоритм так же странен и непонятен. Расскажите как он работает?

**Comment by gipertech** [comment]
Берем полином третьей степени. F(X) = ах^3+Ьх^2+сх+d и его производную f'(x)=3ax^2+2bx+c
Подставим 0 и 1, решим систему и получим формулы для a,b,c,d. Т.е. выразили a,b,c,d через f(0), f'(0), f(1), f'(1).
По факту эти формулы будут являться кубическими интерполяционными формулами для интерполяции между 0 и 1. 
Пример: Пусть есть точки Z0 = -1,Z1 = 0,Z2 = 1,Z3 = 2. И мы хотим проинтерполировать между Z! и Z2. Подставили z1 z2, высчитали коэффициенты.  
Подставили коэф в уравнение интерполяции:
f(z0,z1,z2,z3,x) = (-0.5z0 + 3/2z1 - 3/2z2 + 0.5z3)x^3 + (z0 - 5/2z1 + 2z2 - 0.5z3)x^2 + (0.5z0 + 0.5z2)x + z1
Получили интерполяцию точки. Но косяк, лишь в одном измерении. Нужно добавить второе, чтобы было 4*4.
Но не беда. Мы сначала проинтерполируем четыре строчки. Получим столбец из 4 элементов, и проинтерполируем и его. В итоге, конечное число - бикубическая интерполяция в двух измерениях)

**Comment by pavel-b-novikov** [comment]
А, ну ясно.
